### ISSUE TITLE
Improve password fallback and add more information on key enrollment

### ISSUE THREAD

**Issue by sirtoobii** [blastrock/blastrock.github.io#1]
Dear @blastrock 

Thank you very much for this guide - it really is super useful!  I have two suggestions tough:

- The script to implement the fallback logic is a bit unreliable (e.g. sometimes the input is not accepted or the passphrase is considered wrong). However there is a very clean solution to mitigate this:

```shell
#!/bin/sh
# /etc/initramfs-tools/tpm2-cryptsetup
[ "$CRYPTTAB_TRIED" -lt "1" ] && exec tpm2-initramfs-tool unseal --pcrs 0,2,4,7

/usr/bin/askpass "Passphrase for $CRYPTTAB_SOURCE ($CRYPTTAB_NAME): "
``` 

Since `askpass` is not included per default, it also needs to be added in the initramfs hook script:

```shell
# /etc/initramfs-tools/hooks/tpm2-initramfs-tool
copy_exec /usr/lib/cryptsetup/askpass /usr/bin
```

- Although the enrollment of your own secure-boot keychain is by far the riskiest part (in my case, I would permanently block my device if the Microsoft "db" and "KEK" keys were not included...) this guide does not provide much useful information besides generating the certificates. So it may makes sense to add a link to this very comprehensive guide: https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#Using_your_own_keys (and also mention that users should also use PCR 4 to seal their keys in case they are including factory keys)

**Comment by blastrock** [comment]
Hi,

Thanks a lot for the feedback!

> sometimes the input is not accepted or the passphrase is considered wrong

Yeah, I saw this bug and thought that something was wrong with my system. Then I must admit I got lazy and never tried to fix it haha

The fix you propose looks nice though!

> in my case, I would permanently block my device if the Microsoft "db" and "KEK" keys were not included

I just read the warning in your link, and wow, I didn't think such broken hardware could exist!

I'll patch the guide with your suggestions, thanks again!

**Comment by blastrock** [comment]
I have set up the script, askpass is awesome, it even integrates with plymouth!

I just have a question before I can update the guide:

> and also mention that users should also use PCR 4 to seal their keys in case they are including factory keys

I am not sure what you mean by this. PCR4 depends on the boot loader, and IIUC that's the Linux.efi bundle. Sealing with it would mean that every time one upgrades the kernel, they would have to redo the sealing, right? And I don't understand how that's related to factory keys.

**Comment by sirtoobii** [comment]
> I am not sure what you mean by this. PCR4 depends on the boot loader, and IIUC that's the Linux.efi bundle. Sealing with it would mean that every time one upgrades the kernel, they would have to redo the sealing, right? And I don't understand how that's related to factory keys.

This is only valid if users choose to also enroll the Microsoft and vendor keys (aka "factory keys") since as soon these keys are enrolled, someone could just boot _anything_ which is signed by one of these keys (e.g. a Linux using `shim-signed` or just a windows installer...) which technically does not compromise secure boot (and thus `PCR7` is ok) and as a result, the TPM happily unseals the decryption key. 
Yes, this is inconvenient but as far as I understood, it is the only way to not completely render the full-disk encryption useless while still having third party keys enrolled.

Edit: It just came to my mind that you could also add a link to this github repo somewhere in the guide. This way you can collect fancy stars and probably (and most importantly) get more feedback :)

**Comment by blastrock** [comment]
I see the problem, thanks for the details! On my machine, booting something signed with another key (like the grub shim from microsoft) gives a different value in PCR7, so PCR7 is enough to protect me from people booting other (signed) OSes on my machine. I remember reading about some UEFIs on which PCR7 would have the same value regardless of the key that signed the boot loader. I even wrote this in the guide:

> It looks like some UEFI firmwares do not change PCR7 depending on which signature was found in the bootloader. This defeats the purpose of this guide, and if that's your case... well, you're back to using a passphrase. If you want to check it out before continuing this guide, you should try to run tpm2_pcrread and look at the PCR7 value (SHA1 or SHA256, it doesn't matter here). Run that command after booting through the debian-direct bundle we just created, and after booting through the usual GRUB boot. It should contain two different values.

Using PCR4 is indeed a workaround for this issue, I'll add it. It's better than going back to a passphrase!

> Edit: It just came to my mind that you could also add a link to this github repo somewhere in the guide. This way you can collect fancy stars and probably (and most importantly) get more feedback :)

True, will do!

**Comment by blastrock** [comment]
All fixed, thanks again!
