### ISSUE TITLE
Unnecessary kernel options

### ISSUE THREAD

**Issue by nazar-pc** [blastrock/blastrock.github.io#2]
Looks like neither `rootfstype=ext4` nor `add_efi_memmap` are actually necessary, why are they present?

**Comment by blastrock** [comment]
I must admit I can't remember why I put those, and past-me didn't bother to explain... My guess would be that grub used to put them and I copy pasted them. I'll try removing them on my setup and update the guide.

Thanks for the feedback!

**Comment by nazar-pc** [comment]
I mean they don't hurt, but they are also not necessary either in almost all cases.

**Comment by blastrock** [comment]
Thank you, I just updated the guide with the fixes for the three issues.
