### ISSUE TITLE
Update initramfs-tools hook format

### ISSUE THREAD

**Issue by nazar-pc** [blastrock/blastrock.github.io#3]
My understanding is that initramfs-tools hook is not quite correct, it should have the following prefix:

```
#!/bin/sh -e

PREREQ=""

#Output prequisites
prereqs()
{
    echo "$PREREQ"
}

case $1 in prereqs)
    prereqs
    exit 0;;
esac

```

**Comment by blastrock** [comment]
Are you talking about `/etc/initramfs-tools/hooks/tpm2-initramfs-tool`? Why do you think that? My current hook contains exactly what I wrote in the guide.

**Comment by nazar-pc** [comment]
Yes, that file. Because if you check any other hooks they have exactly the same prefix (or bigger one in case there are actual dependencies). While your example also works in some cases, IIRC it will cause issues some others, but I'm lazy to search when exactly.

**Comment by blastrock** [comment]
I don't have any other hook, so I probably improvised this script. But looking at the doc, the header should be there indeed https://manpages.ubuntu.com/manpages/xenial/man8/initramfs-tools.8.html . I'll fix this, thanks again!
