### ISSUE TITLE
systemd-boot-efi is necessary for linuxx64.efi.stub on Ubuntu 23.10+

### ISSUE THREAD

**Issue by nazar-pc** [blastrock/blastrock.github.io#6]
Not sure if you want to include this information since the guide is for Debian and it might have slightly different packages comparing to Ubuntu, but I found out that for Ubuntu 23.10 `systemd-boot-efi` package needs to be installed for `/usr/lib/systemd/boot/efi/linuxx64.efi.stub` to be present (and for ukify to work) https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2049244

P.S. Ukify will only be available in Ubuntu 24.04: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2031898

**Comment by blastrock** [comment]
Thanks for the reports. It looks like I have that package installed on my debian too, I added a mention in the guide.
